sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t chrislynch96/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chrislynch96/react-test npm test

after_success:
  - docker build -t chrislynch96/multi-client ./client
  - docker build -t chrislynch96/multi-nginx ./nginx
  - docker build -t chrislynch96/multi-server ./server
  - docker build -t chrislynch96/multi-worker ./worker

# Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push chrislynch96/multi-worker
  - docker push chrislynch96/multi-server
  - docker push chrislynch96/multi-nginx
  - docker push chrislynch96/multi-client